### ISSUE TITLE
Failing account setup

### ISSUE THREAD

**Issue by elsbrock** [krambox/moneymoney-ibkr#1]
Finally, great work!

I wanted to give it a spin but failed during account setup; looks like it is using new hosts in my case.
```
22:50:40  Starting account setup assistant.
22:52:26  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension ibkr.lua version 0.10.
          Protocol version: Web Scraping
          Sending: GET https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t=xxx&q=622477&v=3
22:52:27  Unknown hostname gdcdyn.interactivebrokers.com.
          Konnte keine Verbindung zum Server https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t=xxx&q=622477&v=3 aufbauen, da der Servername noch nicht in der Whitelist von MoneyMoney hinterlegt ist.  Bitte wenden Sie sich mit dieser Fehlermeldung an unseren Support, dann werden wir das Problem schnellstmöglich lösen.
```

**Comment by krambox** [comment]
Hello, you must currently disable the signature verification in the extension (this is only possible with the beta of MoneyMoney). With the next release of MoneyMoney the host gdcdyn.interactivebrokers.com will be allowed and then it should be possible directly.

**Comment by att-c** [comment]
Thank you so much for this! I just tried to set it up and am now getting this error:

```
10:02:55  Starting account setup assistant.
10:03:28  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension ibkr.lua version 0.10.
          Protocol version: Web Scraping
          Sending: GET https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t=XXX&q=YYY&v=3
          Received: <FlexStatementResponse timestamp='05 January, 2022 08:03 AM EST'> <Status>Fail</Status> <ErrorCode>1020</ErrorCode> <ErrorMessage>Invalid request or unable to validate request.</ErrorMessage> </FlexStatementResponse> 
          <FlexStatementResponse timestamp='05 January, 2022 08:03 AM EST'> <Status>Fail</Status> <ErrorCode>1020</ErrorCode> <ErrorMessage>Invalid request or unable to validate request.</ErrorMessage> </FlexStatementResponse> 
```

**Comment by krambox** [comment]
First, have you prepared the IBKR Flex Quer and activated the Flex-Web-Service service?
Hav you the IBKR Flex Query id (XXX) und the Flex-Web-Service Token (yyy)
You can fetch the flex report with curl, xxx and yyy you have to modify according to the configuration in IB ?

    curl "https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t=yyy&q=xxx&v=3"

    <FlexStatementResponse timestamp='05 January, 2022 08:21 AM EST'>
    <Status>Success</Status>
    <ReferenceCode>REF_CODE</ReferenceCode>
    <Url>https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.GetStatement</Url>
    </FlexStatementResponse>

Second request, replace REF_CODE with the number in the response.

    curl "https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.GetStatement?t=yyy&q= REF_CODE&v=3" >

**Comment by att-c** [comment]
XXX and YYY were just placeholders. I was indeed using the wrong Flex Query id. Thanks for your help.

**Comment by elsbrock** [comment]
I just updated to the latest beta and it works perfectly for me. I would consider my issue to be resolved.
