### ISSUE TITLE
Wieso vorherige Berichterstattung ausschließen?

### ISSUE THREAD

**Issue by LeFlairGoD** [krambox/moneymoney-ibkr#11]
Da wir von unterschiedlichen MoneyMoney Acounts auf das Depot zugreifen sorgt die Einstellung dafür das immer nur derjenige die Umsätze sieht, der zuerst aktualisiert hat.
Ich habe dies gelöst indem ich es deaktiviert habe und dafür die Abfrage auf die letzten 30 Tage gestellt habe. Alte Umsätze wurden dadurch nicht gelöscht, aber jeder kann nun die Umsätze abrufen.
Maximale Historie ist hierbei jedoch 365 Tage, welche Rückwirkend abgerufen werden können.
Hab ich hierbei irgendetwas nicht bedacht was die zukünftigen Buchungen betrifft?

![image](https://github.com/krambox/moneymoney-ibkr/assets/64659197/b9c829b7-c839-4432-8d21-100492d30a22)

**Comment by Franziska-marker** [comment]
Hallo, ich habe eine Frage zur Anmeldung:
Ich bekomme von IBKR ne .xml Datei aber keinen Token..
Woher bekomme ich den? 
Danke!

**Comment by LeFlairGoD** [comment]
Bei IBKR oben rechts auf Einstellunge und dann Flex Web Service Aktivieren
![image](https://github.com/krambox/moneymoney-ibkr/assets/64659197/ce981ac8-c854-47e6-a4a7-4f966b20349d)

**Comment by Franziska-marker** [comment]
Ich habe immer diese Fehlermeldung..
Was gebe ich unter FlexID ein?

<FlexStatementResponse timestamp='22 June, 2023 02:23 AM EDT'>
<Status>Fail</Status>
<ErrorCode>1020</ErrorCode>
<ErrorMessage>Invalid request or unable to validate request.</ErrorMessage>
</FlexStatementResponse>
