### ISSUE TITLE
Extension nicht sichtbar

### ISSUE THREAD

**Issue by rapha86** [krambox/moneymoney-ibkr#5]
Hallo Kai,

ich benutze einige Erweiterungen in money money, aber diese hier wird nicht geladen, bzw. ist in der Auswahl nicht sichtbar. Weder bei "Add Account", noch in der money money Einstellungen unter "Extensions".
Die ibkr.lua befindet sich im Extension Ordner.

Hast du eine Idee woran es liegen könnte?

Vielen Dank.

Grüße
Raphael

**Comment by krambox** [comment]
Hallo Raphael,

hast du die Erweiterung nicht im Konto hinzufügen Dialog?

Hast du die aktuelle MoneyMoney Version und hast du die signiert Erweiterung ?

![Bildschirmfoto 2022-02-23 um 11 57 50](https://user-images.githubusercontent.com/1663423/155306301-e2a8ba84-7eaa-4f1c-b649-87326a3ef4e9.png)

**Comment by ivankovacevicx** [comment]
> Hallo Kai,
> 
> ich benutze einige Erweiterungen in money money, aber diese hier wird nicht geladen, bzw. ist in der Auswahl nicht sichtbar. Weder bei "Add Account", noch in der money money Einstellungen unter "Extensions". Die ibkr.lua befindet sich im Extension Ordner.
> 
> Hast du eine Idee woran es liegen könnte?
> 
> Vielen Dank.
> 
> Grüße Raphael

Hallo Raphael,
hat bei mir auch nicht funktioniert. 
So geht es aber: die Erweiterung von https://moneymoney-app.com/extensions/ (suche nach "Interactive Brokers") herunterladen und die gegeben Anleitung weiter folgen
Grüße Ivan

**Comment by rapha86** [comment]
Hallo,

vielen Dank für eure Antworten.

Ich habe die Erweiterung hier heruntergeladen:
https://github.com/krambox/moneymoney-ibkr

und die LUA Datei in den Extension Ordner kopiert.

Leider steht die Erweiterung nicht im "Konto hinzufügen" Dialog zur auswahl.

Moneymoney ist aktuell, Version 2.4.10.

@krambox was meinst du mit "signiert Erweiterung"? Benötige ich noch eine weitere Erweiterung, oder muss etwas freigeschaltet werden?

Viele Grüße
Raphael

**Comment by krambox** [comment]
Hallo, die Releaste 0.1 in https://github.com/krambox/moneymoney-ibkr/releases/tag/0.1 hat am Ende im LUA eine Signatur

 -- SIGNATURE: MC0CFBZyTf3ayQ3lCZahDjxYsb8DbWX8AhUAkLzNi07pLujOVhGhtD6HhjjsJeM=

Die aktuelle https://github.com/krambox/moneymoney-ibkr/blob/main/ibkr.lua ist nur mit der folgende Option in MonexMoney ausführbar. 

![image](https://user-images.githubusercontent.com/1663423/158776482-5fe1056f-a0d0-447a-b9c2-99886bf8bbaf.png)

**Comment by rapha86** [comment]
Hallo Kai,

vielen Dank, es funktioniert jetzt! =)

Bei dem Release 0.1 fehlt die Signatur, ich habe sie manuell an das Ende geschrieben und dann wurde die Erweiterung geladen.

Die Konto Einrichtung per Flex hat auch super geklappt, vielen Dank für die tolle Erweiterung an der Stelle!

Viele Grüße
Raphael
