### ISSUE TITLE
ibkr.lua:136: attempt to index local 'summary' (a nil value)

### ISSUE THREAD

**Issue by casper294** [krambox/moneymoney-ibkr#7]
This is the error I get on the v 0.2 release, that was the reason I made the changes in the v 0.1 release

**Comment by marcoschulz** [comment]
Flex-Query has to be changed to include section 'Kapitalflussrechnung (Statement of Funds)'. @krambox

**Comment by krambox** [comment]
Thanks for the feedback. I have fixed the readme.

**Comment by casper294** [comment]
This fixes the issue for me as well, thanks!
